name: PulseCheck CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/PulseCheck.Api/PulseCheck.Api.csproj

      - name: Build
        run: dotnet build src/PulseCheck.Api/PulseCheck.Api.csproj --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build -c Release --verbosity normal
